// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwspdahfoeurzbfekkap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13c3BkYWhmb2V1cnpiZmVra2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDkwMzAsImV4cCI6MjA3MzcyNTAzMH0.v8-xGVlaHEB_0fFRCG9V7s_h9FKlsIMfBEkUedRndow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});